save_dir: ./saved_models
save_name: tmp
resume: False
load_path: saved_models/vc_flexmatch_ce_thr0.85/iter_80000.pth
pseudo_alg: flexmatch
uncertainty_alg: dropout
pseudo_alg_warmup_iter: 45002
cali_train_warmup_iter: 30000
use_cali_out_warmup_iter: 50050
cali_loss_type: ce
lb_strong_aug_warmup_iter: 10
cali_loss_weight: 5.0
num_workers: 0
num_holdout: 0
overwrite: True
use_tensorboard: True
epoch: 100
save_interval: 2500
version: 0
num_train_iter: 1024
num_eval_iter: 500
num_labels: 250
batch_size: 64
eval_batch_size: 1024
hard_label: True
T: 0.5
p_cutoff: 0.85
ulb_loss_ratio: 0.0
uratio: 1
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
net: WideResNetVariationCalibration
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data/cifar10
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
alg: fixmatch
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10010
dist_backend: nccl
gpu: 0
