save_dir: ./saved_models
save_name: vc_lab40_flexmatch_ce_thr0.75
resume: False
load_path: None
pseudo_alg: flexmatch
uncertainty_alg: dropout
pseudo_alg_warmup_iter: 0
cali_train_warmup_iter: 30000
use_cali_out_warmup_iter: 50000
cali_loss_type: ce
cali_loss_weight: 5.0
overwrite: False
num_holdout: 0
use_tensorboard: True
epoch: 100
save_interval: 2500
version: 0
num_train_iter: 1024
num_eval_iter: 2500
num_labels: 40
batch_size: 64
eval_batch_size: 1024
hard_label: True
T: 0.5
p_cutoff: 0.75
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
net: WideResNetVariationCalibration
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data/cifar10
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
alg: fixmatch
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10010
dist_backend: nccl
gpu: 0
