save_dir: ./saved_models
save_name: tmp
resume: False
load_path: None
prob_warmup_iters: 1000000000000
cali_warmup_iters: 1300000000000
overwrite: True
use_tensorboard: True
epoch: 250
version: 0
vc_loss_weight: 0.0
num_train_iter: 1024
num_eval_iter: 5000
num_labels: 250
batch_size: 128
eval_batch_size: 1024
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.06
momentum: 0.9
weight_decay: 0.0005
amp: True
net: WideResNetVariationCalibration
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data/cifar10
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
alg: fixmatch
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10009
dist_backend: nccl
#gpu: 0
